config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "password_resets/new"
  get "password_resets/edit"
  get "/checkout", to: "order_details#checkout"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/help", to: "static_pages#help"

  namespace :admin do
    get "/", to: "sessions#new"
    post "/", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/dashboard", to: "dashboards#index"
    resources :users, only: [:index, :destroy]
    resources :categories, except: :destroy
    resources :products, except: %i(index show destroy)
  end
  resources :users
  resources :account_activations, only: :edit
  resources :password_resets, except: %i(index show)
  resources :products do
    resources :comments
  end
  resources :categories
  resources :carts
  resources :orders
  resources :ratings, only: :create
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: {cancel: 0, pending: 1, delivered: 2}
  belongs_to :user
  has_many :order_details
  has_many :products, through: :order_details
  accepts_nested_attributes_for :order_details, reject_if: :all_blank

  scope :all_order, ->{select :id, :user_id, :created_at, :status}
  scope :order_cancel, ->{where status: :cancel}
  scope :order_pending, ->{where status: :pending}
  scope :order_delivered, ->{where status: :delivered}

  scope :filter_by_status, lambda{ |filter_params|
    case filter_params[:status].presents?
      when filter_params[:status] == "cancel"
        Order.where("status = ?", filter_params[:status])
      when filter_params[:status] == "pending"
        Order.where("status = ?", filter_params[:status])
      when filter_params[:status] == "delivered"
        Order.where("status = ?", filter_params[:status])
    end
  }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::ApplicationController
  def index
    @orders = Order.all_order

    case params[:status].present?
      when params[:status] == "all"
        @orders = @orders
      when params[:status] == "cancel"
        @orders = @orders.order_cancel
      when params[:status] == "pending"
        @orders = @orders.order_pending
      else
        @orders = @orders.order_delivered
    end

    @orders = @orders.page(params[:page]).per(Settings.per.limit_page)

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @order = Order.find_by id: params[:id]
    @items = @order.order_details
  end

  def update
    @order = Order.find_by id: params[:id]
    @order.update_attributes order_params
  end

  private

  def order_params
    params.permit :id, :status
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :logged_in_user, only: %i(create update)
  before_action :load_menu, only: %i(index show)

  def index
    @orders = current_user.orders.all_order
  end

  def show
    @order = Order.find_by id: params[:id]
    @items = @order.order_details
  end

  def create
    @order = current_user.orders.build order_params

    if @order.save
      flash[:success] = t ".success"
      UserMailer.order_success(@order).deliver_now
      session.delete :order_id
      @current_order = nil
      redirect_to root_url
    end
  end

  def update
    @order = Order.find_by id: params[:id]

    if @order.update_attributes order_params
      flash[:sucess] = t ".cancel_success"
      redirect_to request.referer
    end
  end

  private

  def order_params
    params.require(:order).permit(:status,
      order_details_attributes: [:id, :product_id, :quantity, :_destroy])
  end

  def load_menu
    @categories_menu = Category.select :id, :name
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
  def current_order
    @current_order ||= session[:order_id] if session[:order_id]
  end

  def total_cart
    @total_cart = 0;
    @total_price = 0;

    session[:order_id].each do |cart_item|
      @total_cart += cart_item["quantity"]
      @total_price += cart_item["price"].to_f * cart_item["quantity"].to_f
    end
  end

  def init_order
    if session[:order_id]
      @order = Order.new
      session[:order_id].each do |order|
        @order.order_details.build product_id: order["product_id"], quantity: order["quantity"]
      end
    end
  end
end

app/views/admin/orders/_order.html.erb
<table class="orders">
  <tr>
    <th><%= t "status" %></th>
    <th><%= t "user_order" %></th>
    <th><%= t "order_date" %></th>
    <th><%= t "status_order" %></th>
    <th><%= t "action" %></th>
  </tr>
  <% orders.each do |order| %>
    <tr>
      <td><%= order.id %></td>
      <td><%= order.user.name %></td>
      <td><%= l order.created_at, format: :short %></td>
      <td class="status-order-<%= order.id %>"><%= order.status %></td>
      <td>
        <%= select_tag "change-status-order", options_for_select(["cancel", "pending", "delivered"],
          :selected => order.status), {:class => "change-status-order"} %>
        <%= hidden_field_tag :order_id, order.id %>
        <%= link_to admin_order_path(order.id) do %>
          <i class="fa fa-eye" style="font-size:24px"></i>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<div id="pagination" class="text-center">
  <%= paginate orders, theme: "twitter-bootstrap-3" %>
</div>

app/views/admin/orders/index.html.erb
<%= t ".find_order" %>
<select id="order-status">
  <option value="all"><%= t ".all" %></option>
  <option value="cancel"><%= t ".cancel" %></option>
  <option value="pending"><%= t ".pending" %></option>
  <option value="delivered"><%= t ".delivered" %></option>
</select>

<%= form_tag(admin_orders_path, method: :get, remote: true) do %>
  <%= hidden_field_tag :status, "", class: "order-status" %>
  <%= submit_tag t(".filter"), class: "filter-status" %>
<% end %>
<div class="show-order">
  <%= render "admin/orders/order", orders: @orders %>
</div>

app/views/admin/orders/index.js.erb
$('.show-order').html('');
$('.show-order').html('<%= j render "admin/orders/order", orders: @orders %>');

app/views/admin/orders/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <table class="orders">
      <tr>
        <th><%= t "index" %></th>
        <th><%= t ".product" %></th>
        <th><%= t ".order_date" %></th>
        <th><%= t ".quantity" %></th>
      </tr>
      <% @items.each.with_index 1 do |item, index| %>
        <tr>
          <td><%= index %></td>
          <td><%= link_to item.product.name, product_path(item.product_id) %></td>
          <td><%= l item.created_at, format: :short %></td>
          <td><%= item.quantity %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>