config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "password_resets/new"
  get "password_resets/edit"
  get "/checkout", to: "order_details#checkout"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/help", to: "static_pages#help"

  namespace :admin do
    get "/", to: "sessions#new"
    post "/", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/dashboard", to: "dashboards#index"
    resources :users, only: [:index, :destroy]
    resources :categories, except: :destroy
    resources :products, except: %i(index show destroy)
  end
  resources :users
  resources :account_activations, only: :edit
  resources :password_resets, except: %i(index show)
  resources :products do
    resources :comments
  end
  resources :categories
  resources :carts
  resources :orders
  resources :ratings, only: :create
end

app/models/cart.rb
class Cart
  attr_accessor :product_id, :name, :price, :picture, :quantity

  def initialize product_id, name, price, picture, quantity
    @product_id = product_id
    @name = name
    @price = price
    @picture = picture
    @quantity = quantity
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :load_product, only: :create
  before_action :load_menu, only: :index

  def index
    if session[:order_id]
      current_order
      total_cart
      init_order
    end
  end

  def create
    unless session[:order_id].present?
      session[:order_id] = []
    end

    item = Cart.new(@product.id, @product.name, @product.price,
      @product.images.first.picture, Settings.order_details.quantity.default)

    index = session[:order_id].find_index {|n| n["product_id"] == item.product_id}

    if index.nil?
      session[:order_id] << item
    else
      quantity = session[:order_id][index]["quantity"]
      session[:order_id][index]["quantity"] = quantity+1
    end

    @current_order = session[:order_id]

    respond_to do |format|
      format.html {redirect_to root_url}
      format.js
    end
  end

  def update
    session[:order_id].each do |item|
      if item["product_id"] == params[:id].to_i
        item["quantity"] = params["quantity"].to_i
        @sub_price = item["quantity"].to_i * item["price"].to_f
      end
    end
    total_cart
    init_order

    respond_to do |format|
      format.js
    end
  end

  def destroy
    session[:order_id].delete_if{|item| item["product_id"] == params[:id].to_i}
    total_cart
    init_order

    respond_to do |format|
      format.js
    end
  end

  private

  def load_product
    @product = Product.find_by id: params[:product_id]
    redirect_to root unless @product
  end

  def load_menu
    @categories_menu = Category.select :id, :name
  end
end

app/views/carts/checkout.html.erb
<div id="breadcrumb">
  <div class="container">
    <ul class="breadcrumb">
      <li><a href="#">Home</a></li>
      <li class="active">Checkout</li>
    </ul>
  </div>
</div>
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-12 checkout">
        <form id="checkout-form" class="clearfix">
          <div class="order-summary clearfix">
            <div class="section-title">
              <h3 class="title">Order Review</h3>
            </div>
            <table class="shopping-cart-table table">
              <thead>
                <tr>
                  <th>Product</th>
                  <th></th>
                  <th class="text-center">Price</th>
                  <th class="text-center">Quantity</th>
                  <th class="text-center">Total</th>
                  <th class="text-right"></th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td class="thumb"><img src="./img/thumb-product01.jpg" alt=""></td>
                  <td class="details">
                    <a href="#">Product Name Goes Here</a>
                    <ul>
                      <li><span>Size: XL</span></li>
                      <li><span>Color: Camelot</span></li>
                    </ul>
                  </td>
                  <td class="price text-center"><strong>$32.50</strong><br><del class="font-weak"><small>$40.00</small></del></td>
                  <td class="qty text-center"><input class="input" type="number" value="1"></td>
                  <td class="total text-center"><strong class="primary-color">$32.50</strong></td>
                  <td class="text-right">
                    <%= link_to "/admin", class: "main-btn icon-btn" do %>
                      <i class="fa fa-edit"></i>
                    <% end %>
                    <%= link_to "/admin", class: "main-btn icon-btn" do %>
                      <i class="fa fa-close"></i>
                    <% end %>
                  </td>
                </tr>
              </tbody>
              <tfoot>
                <tr>
                  <th colspan="1">TOTAL</th>
                  <th colspan="5" class="total">$97.50</th>
                </tr>
              </tfoot>
            </table>
            <div class="pull-right">
              <button class="primary-btn">Place Order</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/carts/create.js.erb
$('.qty').html(parseInt($('.qty').html())+1);
alert('<%= t("order_details.create.buy_cuccessfully") %>');

app/views/carts/destroy.js.erb
$('.total-quantity').html('<%= @total_cart %>');
$('.cart-item').bind('ajax:success', function(){
  $(this).parents('tr:first') .remove();
})
$('.total-price').html("<%= @total_price %>");
$('.new_order').remove();
$('.form-order').html('<%= j render "orders/order_form", order: @order %>');

app/views/carts/index.html.erb
<div id="breadcrumb">
  <div class="container">
    <ul class="breadcrumb">
      <li>
        <%= link_to t(".home"), root_url %>
      </li>
      <li class="active"><%= t ".checkout" %></li>
    </ul>
  </div>
</div>
<div class="section">
  <div class="container">
    <div class="row">
      <div class="col-md-12 checkout">
        <form id="checkout-form" class="clearfix">
          <div class="order-summary clearfix">
            <div class="section-title">
              <h3 class="title"><%= t "order_review" %></h3>
            </div>
            <table class="shopping-cart-table table">
              <thead>
                <tr>
                  <th></th>
                  <th><%= t ".product" %></th>
                  <th class="text-center"><%= t ".price" %></th>
                  <th class="text-center"><%= t ".quantity" %></th>
                  <th class="text-center"><%= t ".total" %></th>
                  <th class="text-right"></th>
                </tr>
              </thead>
              <tbody>
              <% if @current_order %>
                <% @current_order.each do |cart_item| %>
                  <tr>
                    <td class="thumb"><%= image_tag cart_item["picture"]["url"] %></td>
                    <td class="details">
                      <%= link_to cart_item["name"], product_path(cart_item["product_id"]) %>
                    </td>
                    <td class="price text-center">
                      <strong><%= cart_item["price"] %></strong>
                    </td>
                    <td class="qty text-center">
                      <input type="hidden" value="<%= cart_item['product_id'] %>" />
                      <input class="input" type="number"
                        value="<%= cart_item['quantity']%>" min="1" />
                    </td>
                    <td class="total text-center">
                      <strong class="primary-color price-item-<%= cart_item['product_id'] %>">
                        <%= cart_item["quantity"] * cart_item["price"].to_f %>
                      </strong>
                    </td>
                    <td class="text-right">
                      <%= link_to cart_path(cart_item["product_id"]), method: :delete,
                        remote: true, data: {confirm: t("sure")},
                          class: "main-btn icon-btn cart-item" do %>
                        <i class="fa fa-close"></i>
                      <% end %>
                    </td>
                  </tr>
                <% end %>
              <% end %>
              </tbody>
              <tfoot>
                <tr>
                  <th colspan="1"><%= t ".total" %></th>
                  <th colspan="5" class="total total-price">
                    <%= @total_price %>
                  </th>
                </tr>
              </tfoot>
            </table>
          </div>
        </form>
        <div class="pull-right form-order">
          <% if @current_order %>
            <%= render "orders/order_form", order: @order %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/carts/update.js.erb
$('.total-quantity').html('<%= @total_cart %>');
$('.total-price').html('<%= @total_price %>');
$('.price-item-<%= params[:id]%>').html('<%= @sub_price %>');
$('.new_order').remove();
$('.form-order').html('<%= j render "orders/order_form", order: @order %>');