config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "password_resets/new"
  get "password_resets/edit"
  get "/checkout", to: "order_details#checkout"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/help", to: "static_pages#help"

  namespace :admin do
    get "/", to: "sessions#new"
    post "/", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/dashboard", to: "dashboards#index"
    resources :users, only: [:index, :destroy]
    resources :categories, except: :destroy
    resources :products, except: %i(index show destroy)
  end
  resources :users
  resources :account_activations, only: :edit
  resources :password_resets, except: %i(index show)
  resources :products do
    resources :comments
  end
  resources :categories
  resources :carts
  resources :orders
  resources :ratings, only: :create
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true, uniqueness: {case_sensitive: false}

  before_save :downcase_name

  private

  def downcase_name
    name.downcase!
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
  before_action :logged_in_user_admin
  before_action :load_category, only: %i(show edit update)
  before_action :load_menu, only: %i(index show new edit)

  def index; end

  def show
    @products = @category.products.name_like(params[:product_search]).
      page(params[:page]).per Settings.per.limit_page
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t ".add_success"
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".update_success"
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  private

  def category_params
    params.require(:category).permit :name
  end

  def load_category
    @category = Category.find_by id: params[:id]
    return if @category
      flash[:warning] = t "not_found_cate"
      redirect_to admin_categories_path
  end

  def load_menu
    @categories_menu = Category.select :id, :name
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_menu, only: :show

  def show
    @products = Product.filter_by_category(filter_params).
      page(params[:page]).per(Settings.per.limit_filter)

    respond_to do |format|
      format.html
      format.js
    end
  end

  private

  def filter_params
    params.permit :id, :ram, :hard_disk, :sort
  end

  def load_menu
    @categories_menu = Category.select :id, :name
  end
end

app/views/categories/show.html.erb
<div id="breadcrumb">
  <div class="container">
    <ul class="breadcrumb">
      <li><%= link_to t("home"), root_url %></li>
      <li><a href="#"><%= t "product" %></a></li>
      <li><a href="#"><%= t "category" %></a></li>
    </ul>
  </div>
</div>
<div class="section">
  <div class="container">
    <div class="row">
      <div id="aside" class="col-md-3">
        <div class="aside">
          <h3 class="aside-title"><%= t "ram" %></h3>
          <ul class="size-option option-rams">
            <li>
              <%= link_to "#", class: "button-ram" do %>
                <span><%= t ".32gb" %></span>
                <%= hidden_field_tag :ram, Settings.inputs.max_ram %>
              <% end %>
            </li>
            <li>
              <%= link_to "#", class: "button-ram" do%>
                <span><%= t ".16gb" %></span>
                <%= hidden_field_tag :ram, Settings.inputs.medium_ram %>
              <% end %>
            </li>
            <li>
              <%= link_to "#", class: "button-ram" do %>
                <span><%= t ".8gb" %></span>
                <%= hidden_field_tag :ram, Settings.inputs.low_ram %>
              <% end %>
            </li>
            <li>
              <%= link_to "#", class: "button-ram" do %>
                <span><%= t ".4gb" %></span>
                <%= hidden_field_tag :ram, Settings.inputs.min_ram %>
              <% end %>
            </li>
          </ul>
        </div>
        <div class="aside">
          <h3 class="aside-title"><%= t "screene" %></h3>
          <ul class="size-option option-hard-disk">
            <li>
              <%= link_to "#", class: "button-hard-disk" do %>
                <span><%= t ".ssd" %></span>
              <% end %>
            </li>
            <li>
              <%= link_to "#", class: "button-hard-disk" do %>
                <span><%= t ".hdd" %></span>
              <% end %>
            </li>
          </ul>
          <%= form_tag(category_path(@products[0]["category_id"]), method: :get,
            remote: true) do %>
            <%= hidden_field_tag :sort, "", class: "value-sort" %>
            <%= hidden_field_tag :hard_disk, "", class: "value-hard-disk" %>
            <%= hidden_field_tag :ram, "", class: "value-ram" %>
            <%= submit_tag t(".filter"), class: "filter" %>
          <% end %>
        </div>
      </div>
      <div id="main" class="col-md-9">
        <div class="store-filter clearfix">
          <div class="pull-left">
            <div class="sort-filter">
              <span class="text-uppercase"><%= t "sort_by" %>:</span>
              <select class="input input-sort ">
                <option value=""></option>
                <option value="alphabet"><%= t ".alphabet" %></option>
                <option value="ascending"><%= t ".ascending" %></option>
                <option value="descending"><%= t ".descending" %></option>
              </select>
            </div>
          </div>
        </div>
        <div id="store">
          <div class="row">
            <div class="clearfix visible-md visible-lg"></div>
            <div class="show-category">
              <%= render "products/product", products: @products %>
            </div>
            <div class="clearfix visible-sm visible-xs"></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.js.erb
$('.show-category').html('');
$('.show-category').html('<%= j render "products/product", products: @products %>');