config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "password_resets/new"
  get "password_resets/edit"
  get "/checkout", to: "order_details#checkout"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/help", to: "static_pages#help"

  namespace :admin do
    get "/", to: "sessions#new"
    post "/", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/dashboard", to: "dashboards#index"
    resources :users, only: [:index, :destroy]
    resources :categories, except: :destroy
    resources :products, except: %i(index show destroy)
  end
  resources :users
  resources :account_activations, only: :edit
  resources :password_resets, except: %i(index show)
  resources :products do
    resources :comments
  end
  resources :categories
  resources :carts
  resources :orders
  resources :ratings, only: :create
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :comments
  has_many :ratings
  has_many :order_details
  has_many :orders, through: :order_details
  has_many :images

  belongs_to :category

  enum status: {hide: 0, active: 1}
  enum feature: {normal: 0, hot: 1}

  validates :name, presence: true,
    length: {minimum: Settings.product.name.min_length},
      uniqueness: {case_sensitive: false}
  validates :describe, presence: true,
    length: {minimum: Settings.product.describe.min_length}
  validates :price, presence: true
  validates :category_id, presence: true
  validates :images, presence: true

  accepts_nested_attributes_for :images, allow_destroy: true

  scope :feature_hot, ->{where feature: :hot}

  scope :limit_num, ->(num){limit num}

  scope :order_created, ->{order "created_at DESC"}

  scope :order_price, ->{order :price}

  scope :name_like, ->(search){
    if search.present?
      where "name LIKE ?", "%#{search}%"
    end
  }

  scope :filter, ->(min, max){where("price > ? and price < ?", min, max)}
  scope :filter_ram, ->(ram){where "RAM <= ?", ram}
  scope :filter_hard_disk, ->(hard_disk){where "hard_disk = ?", hard_disk}
  scope :sort_alphabet, ->{order :name}
  scope :sort_asc, ->{order price: :asc}
  scope :sort_desc, ->{order price: :desc}
  scope :mail_product, ->(product_ids){
    where("id in (?)", product_ids).select(:id, :name, :price)
  }

  scope :filter_by_category, lambda{ |filter_params|
    products = Product.where("category_id = ?", filter_params[:id].to_i)

    products = products.where("RAM <= ?", filter_params[:ram].to_i) if filter_params[:ram].to_i != 0
    products = products.where("hard_disk = ?", filter_params[:hard_disk]) if filter_params[:hard_disk].present?

    case filter_params[:sort].present?
      when filter_params[:sort] == "alphabet"
        products = products.order(:name)
      when filter_params[:sort] == "ascending"
        products = products.order(price: :asc)
      else
        products = products.order(price: :desc)
    end

    products
  }

  private

  def picture_size
    if picture.size > Settings.product.picture.max_size.megabytes
      errors.add(:picture, I18n.t("image_max"))
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::ApplicationController
  before_action :logged_in_user_admin
  before_action :load_menu, except: %i(index show destroy)
  before_action :load_product, only: %i(edit update)

  def new
    @product = Product.new
    @product.images.build
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = t ".add_success"
      redirect_to admin_dashboard_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @product.update_attributes product_params
      flash[:success] = t ".update_success"
      redirect_to admin_category_path @product.category
    else
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :describe, :price, :discount,
      :feature, :RAM, :screen, :hard_disk, :status, :category_id, images_attributes: [:id, :picture, :_destroy])
  end

  def load_menu
    @categories_menu = Category.select :id, :name
  end

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product
    flash[:warning] = t "not_found_product"
    redirect_to admin_dashboard_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_menu, only: [:index, :show]
  before_action :load_product, only: :show

  def index
    if params[:product_search].present?
      @products = Product.name_like(params[:product_search]).page(params[:page]).
      per Settings.per.product.limit_page
    else
      @products = Product.filter(params[:floor].to_i, params[:ceil].to_i).
        page(params[:page]).per(Settings.per.limit_page)
    end
    return if @products.present?
    flash[:warning] = t ".not_exist"
    redirect_to root_url
  end

  def show
    @rate = @product.ratings.average(:rate)
    if params[:comment_limit].present?
      @comments = @product.comments.more_than(params[:comment_limit]).
      limit_num Settings.comments.limit_show
    else
      @comments = @product.comments.limit_num Settings.comments.limit_show
    end
    respond_to do |format|
     format.html
     format.js
    end
  end

  private

  def load_menu
    @categories_menu = Category.select :id, :name
  end

  private

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product
    flash[:warning] = t "product_not"
    redirect_to root_path
  end
end

app/views/products/_product.html.erb
<div class="row">
  <% products.each do |product| %>
    <div class="product product-single col-md-4">
      <div class="product-thumb">
        <%= link_to image_tag(product.images.first.picture,
          alt: t(".alt_image"), size: Settings.product.picture.size), product_path(product) %>
      </div>
      <div class="product-body">
        <h3 class="product-price">
          <%= number_to_currency product.price, unit: t("vnd"),
            precision: 0, format: "%n %u" %>
        </h3>
        <div class="product-rating">
          <i class="fa fa-star"></i>
          <i class="fa fa-star"></i>
          <i class="fa fa-star"></i>
          <i class="fa fa-star"></i>
          <i class="fa fa-star-o empty"></i>
        </div>
        <h2 class="product-name"><%= link_to product.name, product_path(product) %></h2>
        <div class="product-btns">
          <%= link_to carts_path(product_id: product.id),
            method: :post, remote: true, class: "primary-btn add-to-cart" do  %>
            <i class="fa fa-shopping-cart"></i>
            <%= t "add_to_cart" %>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div id="pagination" class="text-center">
  <%= paginate @products, theme: "twitter-bootstrap-3" %>
</div>

app/views/products/index.html.erb
<div class="section">
  <div class="container list_product">
    <div class="row">
      <div class="col-md-12 col-sm-6 col-xs-6">
        <%= render "products/product", products: @products %>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div id="breadcrumb">
  <div class="container">
    <ul class="breadcrumb">
      <li><%= link_to t("home"), root_path %></li>
      <li><%= t "product" %></li>
    </ul>
  </div>
</div>
<div class="section">
  <div class="container">
    <div class="row">
      <div class="product product-details clearfix">
        <div class="col-md-6">
          <div id="product-main-view">
            <% @product.images.each do |pro| %>
              <div class="product-view">
                <%= image_tag pro.picture %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="col-md-6">
          <div class="product-body">
            <div class="product-label">
              <span><%= t "detail" %></span>
            </div>
            <h2 class="product-name"><%= @product.name %></h2>
            <div class="rating_success"></div>
            <% if @rate %>
              <span class="total-star">
                <%= "%.1f" % @rate %> <i class="fa fa-star"></i>
              </span>
            <% end %>
            <% if logged_in? %>
              <div class="stars">
                <%= form_for :rating, url: ratings_path, method: :post, remote: true do |rating| %>
                  <%= rating.hidden_field :product_id, value: @product.id %>
                  <% 5.times do |rate| %>
                    <%= rating.radio_button :rate, 5-rate, class: "star star-#{5-rate}", id: "star-#{5-rate}" %>
                    <label class="star star-<%= 5-rate %>" for="star-<%= 5-rate %>" title="star-<%= 5-rate %>"></label>
                  <% end %>
                  <%= rating.submit name: "star_button", class: "star_button" %>
                <% end %>
              </div>
            <% else %>
              <%= t "rating_login" %>
              <%= link_to t("login"), login_path,
                {remote: true, data: {toggle: "modal", backdrop: "static", keyboard: "false", target: "#login"}} %>
            <% end %>
            <p>
              <strong><%= t ".price" %>: </strong>
              <%= number_to_currency @product.price, unit: t("vnd"),
              precision: 0, format: "%n %u" %>
            </p>
            <% if @product.screen %>
              <p><strong><%= t ".ram" %></strong>: <%= @product.RAM %></p>
              <p><strong><%= t ".screen" %></strong>: <%= @product.screen %></p>
              <p><strong><%= t ".hard_disk" %></strong>: <%= @product.hard_disk %></p>
            <% end %>
            <div class="product-btns">
              <%= link_to carts_path(product_id: @product.id),
                    method: :post, remote: true, class: "primary-btn add-to-cart" do %>
                 <i class="fa fa-shopping-cart"></i> <%= t "add_to_cart" %>
              <% end %>
            </div>
          </div>
        </div>
        <div class="col-md-12">
          <div class="product-tab">
            <ul class="tab-nav">
              <li class="active">
                <%= link_to t("description"), "#tab1", data: {toggle: "tab"} %>
              </li>
            </ul>
          </div>
          <div class="tab-content">
            <div id="tab1" class="tab-pane fade in active">
              <p>
                <%= @product.describe %>
              </p>
            </div>
          </div>
        </div>
        <div class="col-md-12" id="comments" >
          <div id="alert_error_comment"></div>
          <h3 class="title_comment"><%= t "comment" %></h3>
          <%= render partial: "comments/comment", collection: @comments %>
        </div>
        <% if @comments.any? %>
          <div id="button_show" class="col-md-12">
            <%= link_to t("show"), product_path(@product,
              comment_limit: @comments.last.id),
              remote: true, method: :get, class: "btn_show_more" %>
          </div>
        <% end %>
        <div id="error_length" class="col-md-12 red-req">&nbsp;</div>
        <div class="col-md-12 comment_form">
          <%= render "shared/comment_form", product: @product %>
        </div>
      </div>
    </div>
  </div>
</div

app/views/products/show.js.erb
<% if @comments.any? %>
  $('#button_show').remove();
  $('#comments').find('.btn_show_more').remove();
  $('#comments').append('<%= j render @comments %>');
  $('#comments').
  append('<%= link_to t("show"), product_path(@product, comment_limit: @comments.last.id), remote: true, method: :get, class: "btn_show_more" %>');
<% else %>
  $('.btn_show_more').remove();
<% end %>